# Generated by Django 2.2.6 on 2019-11-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureSet', '0002_furnituresetmodel_itemlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurnitureImage',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('furnitureSetCode', models.CharField(max_length=10)),
                ('image', models.ImageField(default='Images/None/No-image.jpg', upload_to='Images/FurnitureSet/')),
            ],
        ),
    ]
