# Generated by Django 2.2.6 on 2019-12-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureSet', '0005_furnituresetmodel_roomtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnituresetmodel',
            name='name',
            field=models.TextField(default='RoomSet I'),
        ),
        migrations.AddField(
            model_name='furnituresetmodel',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
