# Generated by Django 2.2.6 on 2019-10-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('productCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('furnitureType', models.CharField(default=None, max_length=20)),
                ('brand', models.CharField(default=None, max_length=20)),
                ('size', models.IntegerField(default=None)),
                ('color', models.CharField(default=None, max_length=10)),
                ('description', models.CharField(default=None, max_length=255)),
                ('imagePath', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
