# Generated by Django 2.2.6 on 2019-10-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='imagePath',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(default='Images/None/No-image.jpg', upload_to='Images/'),
        ),
    ]
