# Generated by Django 2.2.6 on 2019-10-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191031_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(default='Images/None/No-image.jpg', upload_to='Images/'),
        ),
    ]
