# Generated by Django 2.2.6 on 2019-11-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20191031_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('productCode', models.CharField(max_length=10)),
                ('image', models.ImageField(default='Images/None/No-image.jpg', upload_to='Images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='image',
        ),
    ]
