# Generated by Django 2.2.6 on 2019-12-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20191111_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='size',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
