# Generated by Django 2.2.6 on 2019-12-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20191214_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='brand',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='color',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='furnitureType',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='size',
            field=models.TextField(default=None),
        ),
    ]
